name: Frontend Azure Static Web App CI/CD

trigger:
- main

variables:
  nodeVersion: '20.x'
  appLocation: '/src' # Updated to point to the src directory where React code is
  outputLocation: 'build' # React build output directory
  apiLocation: '' # Leave empty as this is frontend only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# Add diagnostic step to verify build directory
- script: |
    pwd
    ls -la
    echo "Changing to src directory..."
    cd src
    ls -la
  displayName: 'List Working Directory'

- script: |
    cd src
    npm install
    npm run build
  displayName: 'npm install and build'

# Verify build output
- script: |
    echo "Checking build output..."
    cd src
    ls -la
    ls -la build || echo "Build directory not found!"
  displayName: 'Verify Build Output'

# Verify deployment variables
- script: |
    echo "Checking deployment configuration..."
    echo "Current directory: $(pwd)"
    echo "App Location exists: $([[ -d "src" ]] && echo 'Yes' || echo 'No')"
    echo "Build directory exists: $([[ -d "src/build" ]] && echo 'Yes' || echo 'No')"
    echo "Token is set: $([[ ! -z "$(deployment_token)" ]] && echo 'Yes' || echo 'No')"
    echo "Token length: ${#deployment_token}"
  displayName: 'Verify Deployment Configuration'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment_token)
    app_location: $(appLocation)
    output_location: $(outputLocation)
    api_location: $(apiLocation)
    skip_app_build: false
    verbose: true
  displayName: 'Deploy to Azure Static Web App'
  env:
    DEBUG: 'true' 