name: Frontend Azure Static Web App CI/CD

trigger:
- main

variables:
  nodeVersion: '20.x'
  appLocation: '/' # Location of your React app code
  outputLocation: 'build' # React build output directory
  apiLocation: '' # Leave empty as this is frontend only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment_token)
    app_location: $(appLocation)
    output_location: $(outputLocation)
    api_location: $(apiLocation)
    skip_app_build: false
  displayName: 'Deploy to Azure Static Web App' 