# ASP.NET Core with React
# Build and test ASP.NET Core project and deploy
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # The deployment_token is configured in Azure Pipeline variables
  # Do not define the token here for security reasons

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '7.x'
    includePreviewVersions: true
  displayName: 'Install .NET Core SDK'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  displayName: 'NuGet restore'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'dotnet publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish artifacts'

# Example of using the deployment token securely
- script: |
    echo "Using deployment token securely"
    # Access the token using $(DEPLOYMENT_TOKEN)
    # Example: dotnet nuget push *.nupkg --api-key $(DEPLOYMENT_TOKEN)
  env:
    DEPLOYMENT_TOKEN: $(deployment_token)  # Reference the variable securely
  displayName: 'Deploy with token' 