name: Frontend Azure Static Web App CI/CD

trigger:
- main

variables:
  nodeVersion: '20.x'
  appLocation: '/' # Root of your app
  outputLocation: 'build' # React build output directory
  apiLocation: '' # Leave empty as this is frontend only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# Add diagnostic step to verify directory structure
- script: |
    echo "Checking repository structure..."
    pwd
    ls -la
    echo "Verifying package.json exists..."
    if [ -f "package.json" ]; then
      echo "package.json found"
      cat package.json
    else
      echo "package.json NOT found!"
      exit 1
    fi
  displayName: 'List Working Directory'

- script: |
    npm ci
    npm run build
  displayName: 'npm install and build'

- script: |
    echo "Verifying build output structure:"
    ls -la build/
    echo "Checking for index.html:"
    if [ -f "build/index.html" ]; then
      echo "index.html found in build directory"
    else
      echo "index.html NOT found in build directory!"
      exit 1
    fi
  displayName: 'Verify Build Output'

# Verify deployment variables (without exposing sensitive data)
- script: |
    echo "Checking deployment configuration..."
    echo "Current directory: $(pwd)"
    echo "Package.json exists: $([[ -f "package.json" ]] && echo 'Yes' || echo 'No')"
    echo "Build directory exists: $([[ -d "build" ]] && echo 'Yes' || echo 'No')"
    # Don't echo the actual token for security
    echo "Token is configured: $([[ ! -z "$(deployment)" ]] && echo 'Yes' || echo 'No')"
  displayName: 'Verify Deployment Configuration'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment)
    app_location: '/'
    output_location: 'build'
    api_location: ''
    skip_app_build: true # We're building the app in previous steps
    verbose: true
  displayName: 'Deploy to Azure Static Web App'
  condition: and(succeeded(), ne(variables['deployment'], ''))