name: Frontend Azure Static Web App CI/CD

trigger:
- main

variables:
  nodeVersion: '20.x'
  appLocation: '/' # Location of your React app code
  outputLocation: 'build' # React build output directory
  apiLocation: '' # Leave empty as this is frontend only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Verify environment before deployment
- script: |
    echo "Checking deployment environment..."
    echo "App Location: $(appLocation)"
    echo "Output Location: $(outputLocation)"
    echo "Node Version: $(nodeVersion)"
    echo "Deployment token is set: $([[ ! -z '$(deployment_token)' ]] && echo 'Yes' || echo 'No')"
  displayName: 'Verify Deployment Environment'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment_token)
    app_location: $(appLocation)
    output_location: $(outputLocation)
    api_location: $(apiLocation)
    skip_app_build: false
    verbose: true
  displayName: 'Deploy to Azure Static Web App'
  env:
    DEBUG: 'true' 